# Generated by Django 3.1.3 on 2021-05-16 03:31

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210422_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='camera',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='location_info',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
