# Generated by Django 3.0.14 on 2021-05-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210516_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='love',
            field=models.BooleanField(default=False),
        ),
    ]
