# Generated by Django 3.0.14 on 2021-05-26 09:11

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_love'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='KR', max_length=2, null=True),
        ),
    ]
