# Generated by Django 3.0.14 on 2021-05-26 09:12

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210526_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='KR', max_length=2),
        ),
    ]
